In [1]:
import numpy as np

a_1d = np.random.randint(1, 100, 5)
b_1d = np.random.randint(1, 100, 5)
c_1d = [-1]
d = -1

a_2d = np.random.randint(1, 100, (2, 2))
b_2d = np.random.randint(1, 100, (2, 2))

print(a_1d, b_1d, c_1d, d, a_2d, b_2d, sep='\n')

[52 74 61 89 34]
[51 58 84 89 83]
[-1]
-1
[[87 95]
 [43 43]]
[[ 8 55]
 [73 93]]


In [2]:
# array: thực hiện phép toán trên từng phần tử -> elem by elem
print(a_1d + b_1d)
print(a_1d + c_1d) # broatcast: ma trận nhỏ hơn sẽ tự mở rộng để phù hợp kích thước (NẾU CÓ THỂ)
print(a_1d + d) # broatcast

print(a_2d + b_2d)
print(a_2d + c_1d) 
print(a_2d + d)
# tương tự, có các phép +,- , *, /, //, %, **

# @ -> hoặc np.dot()
print(a_1d @ b_1d)
print(a_2d @ b_2d)


[103 132 145 178 117]
[51 73 60 88 33]
[51 73 60 88 33]
[[ 95 150]
 [116 136]]
[[86 94]
 [42 42]]
[[86 94]
 [42 42]]
22811
[[ 7631 13620]
 [ 3483  6364]]


In [3]:
# sử dụng built-in function
# np.add(), subtract, multiply, divide, floor_divide, mod, power
print(np.add(a_1d, c_1d)) # add(x, y, out=None)
print(np.mod(a_2d, b_2d))

[51 73 60 88 33]
[[ 7 40]
 [43 43]]


In [4]:
#compare
print(a_1d == b_1d)
# ==, !=, >, >=, <, <=
# np.equal(), np.not_equal

# bitwise
print(a_1d & 1)
# &, !, ^, ~
# logical_and(), logical_or, logical_xor, logical_not

[False False False  True False]
[0 0 1 1 0]


In [5]:
# một số hàm toán học nâng cao
print(np.sqrt(a_1d))
print(np.exp(a_1d)) # e^a
# np.log(), np.log10(), np.log(2)
# np.abs()

# round(), floor(), ceil()
float_arr = np.random.rand(5)
print(np.round(float_arr, 2))

#sin, cos,tan
# arcsin, arccos, arctan
# dot -> dotproduct
# matmul -> matrix multiply
# sum, min, max ,mean, 


[7.21110255 8.60232527 7.81024968 9.43398113 5.83095189]
[3.83100800e+22 1.37338298e+32 3.10429794e+26 4.48961282e+38
 5.83461743e+14]
[0.82 0.02 0.93 0.22 0.55]


In [6]:
# multiply vs dot product
a = np.random.randint(1, 10, 3)
b = np.random.randint(1, 10, 3)

c = np.asmatrix(np.random.randint(1, 10, 3)) # asmatrix : biiến np.array -> np.matrix
d = np.asmatrix(np.random.randint(1, 10, (3, 1)))
# np.matrix => trả về ma trận, không phải array

# với toán tử *
# a, b là array => a * b => nhân từng phần tử
print(a * b)
# c, d là np.matrix => a * b là matrix multiply
print(c * d) # (1, 3) x (3, 1) => (1, 1)

# vói @ 
# a, b là np.array, 1D array => dot product -> result = a1*b1 + a2 * b2 + a3*b3 + ....
print(a @ b) # -> number
# a, b là np.array, 1 trong 2 or cả 2 không phải 1D arr => matrix multiply
e = np.array([1, 2])
f = np.array([[1, 2], [3, 4]])
print(e@f)

# np.dot -> thực hiện dot product # số cột của A = số hàng (hoặc số phần tử nếu là 1D) của B
a = [[1, 2, 3], [4, 5, 6]]
b = [1, 3, 5]
c = [[4, 2], [7, 1], [8, 9]]
print(np.dot(a, b)) # -> 2x1  # [22 49]
print(np.dot(a, c)) # -> 2x2 # [[42 31], [99 67]]

[18  7 12]
[[106]]
37
[ 7 10]
[22 49]
[[42 31]
 [99 67]]


In [7]:
# cummulative sum / prefix sum -> tổng tích lũy
a = np.array([1, 3, 5])
b = np.array([[1, 2, 3], [4, 5, 6]])

print(a.cumsum()) # [1, 1 + 3 = 4, 4 + 5 = 9] => [1, 5, 9]
print(b.cumsum()) # [1, 1 + 2 = 3, 3 + 3 = 6, 6 + 4 = 10, 10 + 5 = 15, 15 + 6 = 21] => [1, 3, 6, 10, 15, 21]

# cumsum( axis ) -> trả về arr có kích thước không đổi
# axis = 0 => cumsum trên từng cột
print(b.cumsum(axis=0)) # [[1, 2, 3], [1 + 4, 2 + 5, 3 + 6]]
# axist = 1 => cumsum trên từng hàng
print(b.cumsum(axis=1)) # [[1, 1+2, 1+2+3], [4, 4+5, 4+5+6]]

[1 4 9]
[ 1  3  6 10 15 21]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]
