In [2]:
import numpy as np

In [3]:
# using np.array()
a = np.array([1, 2, 3]) # from array
print(a)

a = np.array((1, 2, 3)) # from tuple
print(a)

a = np.array([[1, 2], [3, 4]]) # 2D array

[1 2 3]
[1 2 3]


In [10]:
# using numpy built-in function 
a = np.zeros((2)) # np.zeros(size)
print(a)

a = np.ones((2)) # np.ones(size)
print(a) 

a = np.full((2, 2), 5) # np.full(size, fill_value)
print(a)

a = np.eye(2) # np.eye(dimension)
print(a)

[0. 0.]
[1. 1.]
[[5 5]
 [5 5]]
[[1. 0.]
 [0. 1.]]


In [24]:
# create a list 
print(np.arange(0, 10)) # np.arange(start, end, step)
 
print(np.linspace(0, 2, 4)) # np.linspace(start, end, number_of_elems, endpoint=True) -> 4 số từ 0 tới 2 (chia đều)

print(np.logspace(1, 3, 4)) # np.logspace(start, stop, num, endpoint=True, base=10) -> tạo num số phân bố đều từ base**start tới base**end
# endpoint: boolean -> lấy giá trị cuối cùng trong khoảng? 

[0 1 2 3 4 5 6 7 8 9]
[0.         0.66666667 1.33333333 2.        ]
[  10.           46.41588834  215.443469   1000.        ]


In [120]:
# using random
# np.random.seed(13) # sử dụng seed để mỗi lần chạy cho kết quả random giống nhau, tham số của seed có thể là bất cứ số nào

print(np.random.rand(2, 3)) # sinh 2x3 array các giá trị trong [0, 1) -> .rand(n_dimensions)
# tương tự: np.random.random((2, 3)) -> .random(shape)

print(np.random.randint(3, 13, size=(2, 2))) # randint(start, stop, size)
# -> sinh số nguyên trong [0, 13) vào mảng 2x2

# sinh theo Phân phối chuẩn
a = np.random.randn(2, 2) # sinh mảng 2x2 từ N(0, 1)
print(a)
# hoặc
a = np.random.normal(loc=3, scale=13, size=5) # loc=0, scale=1 -> randn 
# sinh 1D array có 5 phần tử theo phân phối chuẩn với :
# giá trị kỳ vọng (loc) = 2
# độ lẹch chuẩn (scale) = 3
# phân bố chuẩn N(loc, scale**2)
print(a)
# các tham só của phân bố chuẩn
print(a.mean(), a.var(), a.std()) # trung bình, phương sai, độ lẹch chuẩn

# xáo trộn phần tử của 1 array
np.random.shuffle(a)
print(a)

# chọn
a = 13
print(np.random.choice(a, size=3))
a = np.arange(10)
print(np.random.choice(a, size=5, replace=True))
# .choice(a, size, replace=True) 
# a là số -> chọn trong [0, a-1)
# a là array -> chọn phần tử từ array
# replace: cho phép chọn trùng ?

[[6.56455335e-01 5.09262200e-01 4.79883391e-01]
 [9.55574145e-01 1.20335695e-05 2.46978701e-01]]
[[9 7]
 [6 8]]
[[-1.06607    -0.14521133]
 [ 0.23785784 -1.63909341]]
[ -0.61574871  21.19009946 -17.99640352   9.38133382  27.60564884]
7.912985978403064 262.05490767133404 16.188110071016137
[  9.38133382  27.60564884 -17.99640352  -0.61574871  21.19009946]
[11  4 10]
[5 9 4 3 6]


### Read more about:
- `np.loadtxt()` → đọc dữ liệu từ file text.

- `np.genfromtxt()` → đọc CSV.

- `np.load()` → đọc file .npy.