# Indexing, Slicing

In [53]:
import numpy as np

a = np.random.randint(1, 100, (3, 3)) # tạo ma trận 3x3 các số ngẫu nhiên trong [1, 100)
b = np.random.randint(1, 100, 3)

print(a)
print(b)

[[ 6 47 16]
 [35  1 49]
 [27  7 42]]
[72 28 89]


In [54]:
# truy cap phan tu thong qua index
print()
print(a[1])
print(a[1, 1]) 
print(a[-1]) # a[2]
print(a[-3, -3]) # a[0, 0]




[35  1 49]
1
[27  7 42]
6


In [55]:
#boolean indexing -> 1D array
print()
print(b>50) # print boolean value
print(b[b>50]) # print elem that has boolean value is true
odd_in_a = a[a % 2 == 1]
print(a % 2)
print(odd_in_a)




[ True False  True]
[72 89]
[[0 1 0]
 [1 1 1]
 [1 1 0]]
[47 35  1 49 27  7]


In [56]:
# .where() -> same size, modified values
print()
# np.where(condition, value_if_true, value_if_false)
# nếu chỉ truyền condition => trả về array([indexs]) thỏa mãn condition dạng tuple
# ex: (array([0, 0, 0, 1, 1, 1, 2]), array([0, 1, 2, 0, 1, 2, 1])) -> (0, 0), (0, 1), (0, 2) ... .
indexs = np.where(a%2 == 1)
values = np.where(a%2 == 1, a, -1) # true -> elem tuong ung, false -> -1 # a[indexs]
print(indexs)
print(values)
# argwhere() # trả về mảng 2 chiều các tọa độ
print(np.argwhere(a > 50))



(array([0, 1, 1, 1, 2, 2]), array([1, 0, 1, 2, 0, 1]))
[[-1 47 -1]
 [35  1 49]
 [27  7 -1]]
[]


In [57]:
print()
# fancy index: truy cập nhiều phần tử trong 1 lần gọi
# => arr[[index_list]]
print(a[(0, 1), (1, 1)])
print(b[[0, 2]])




[47  1]
[72 89]


In [58]:
# slicing
print()
# ma trận n chiều => chỉ ra khoảng cho từng chiều
print(b[:]) # print(b)
print(b[0:2]) # [0, 2) => [0, 1]
print(a[1:, 2]) # lấy phần từ thứ 3 tại hàng 1, 2
print(a[:, :2]) # lấy phần từ 0, 1 tại tất cả các hàng




[72 28 89]
[72 28]
[49 42]
[[ 6 47]
 [35  1]
 [27  7]]


In [59]:
# slice is reference:
print(f'a = {a}')
aa = a[1:]
print(f'aa = {aa}')
aa[0, 0] = -1 # thay a[0, 0] = -1 -> a[1, 0] = -1
print(f'aa = {aa}')
print(f'a = {a}')

a = [[ 6 47 16]
 [35  1 49]
 [27  7 42]]
aa = [[35  1 49]
 [27  7 42]]
aa = [[-1  1 49]
 [27  7 42]]
a = [[ 6 47 16]
 [-1  1 49]
 [27  7 42]]
