# numpy.linalg


In [1]:
import numpy as np

a = np.random.randint(1, 10, (3, 2, 2))
b = np.random.randint(1, 10, (2, 2))
print(a)
print(b)

[[[3 2]
  [8 5]]

 [[2 5]
  [7 6]]

 [[9 8]
  [9 6]]]
[[5 6]
 [5 8]]


In [2]:
# inv -> ma tran nghich dao
print(np.linalg.inv(a)) # Last 2 dimensions of the array must be square
print(np.linalg.inv(b))

[[[-5.          2.        ]
  [ 8.         -3.        ]]

 [[-0.26086957  0.2173913 ]
  [ 0.30434783 -0.08695652]]

 [[-0.33333333  0.44444444]
  [ 0.5        -0.5       ]]]
[[ 0.8 -0.6]
 [-0.5  0.5]]


In [3]:
# det -> Định thức của ma trận
print(np.linalg.det(a))
print(np.linalg.det(b))

[ -1. -23. -18.]
9.999999999999998


In [16]:
# solve -> ax=b
# ex: 
# x1 + 2x2 = 5
# 5x1 + 3x2 = 20
a = np.array([[1, 2], [5, 3]])
b = np.array([5, 20])

print(np.linalg.solve(a, b)) # [x1 x2]

[3.57142857 0.71428571]


# Read more about: [numpy.linalg](https://numpy.org/doc/stable/reference/routines.linalg.html)