# array.reshape(new_shape)

# copying:
- array assignment
- array`.view()`
- array`.copy()`

# array.concatenate()

In [1]:
import numpy as np

a = np.random.randint(1, 100, 6) # 1D arrray, 4 elems
b = np.random.randint(1, 100, (3, 4)) # 2D 3x4 array
print(a)
print(b)

[ 7 66 17 81 39 47]
[[15 17 69 96]
 [24 47 82 45]
 [92 52 89 58]]


### reshaping array

In [2]:
# .reshape(new_shape)
# shape mới phải có số phần tử bằng shape cũ
print(f'>>> a.shape = {a.shape}')
print(f'>>> b.shape = {b.shape}\n')

# 1. change directly a.shape = new_shape, thay đổi trực tiếp array
a.shape = 1, -1 # or = (1, -1) # chuyển thành 2D, 1 hàng, 6 cột
print(a, f'a.shape = {a.shape}', sep=' ----- ')
print()
# với array n chiều, cần xác định n-1 chiều, chiều còn lại có thể truyền -1 để numpy tự tính số phần tử
# new_shape chỉ được chứa nhiều nhất 1 đối số có giá trị -1

# 2, use .reshape() => trả về array mới, không thay đổi array
a = a.reshape(3, -1, 1) # 3D array, 3xAutox1
print(a, f'a.shape = {a.shape}', sep=' ----- ')
a = a.reshape(-1) # chuyển về 1D array
print(a, f'a.shape = {a.shape}', sep=' ----- ')
print()

# biến về mảng 1 chiều sử dụng ravel(), flatten() -> trả về array mới
print(b.flatten()) 
print(b.ravel())
print(b)

# reshape -> reference
# flatten -> copy
# revel -> view

>>> a.shape = (6,)
>>> b.shape = (3, 4)

[[ 7 66 17 81 39 47]] ----- a.shape = (1, 6)

[[[ 7]
  [66]]

 [[17]
  [81]]

 [[39]
  [47]]] ----- a.shape = (3, 2, 1)
[ 7 66 17 81 39 47] ----- a.shape = (6,)

[15 17 69 96 24 47 82 45 92 52 89 58]
[15 17 69 96 24 47 82 45 92 52 89 58]
[[15 17 69 96]
 [24 47 82 45]
 [92 52 89 58]]


### copying array

In [3]:
# array assignment -> gán THAM CHIẾU (reference) của đối số cho biến được gán
a_ref = a
print(f'>>> a_ref : {a_ref}')
print(f'>>> a : {a}')
print()

# -> mọi thay đổi của a_ref đều ảnh hưởng tới a và ngược lại
# change one element
a_ref[0] = -1 
a[1] = -1
print(f'>>> a_ref : {a_ref}')
print(f'>>> a : {a}')
print()
# change shape
a_ref.shape = 2, -1 # 2D array
print(f'>>> a_ref : {a_ref}')
print(f'>>> a : {a}')
print()

a.shape = -1 # 1D array
print(f'>>> a_ref : {a_ref}')
print(f'>>> a : {a}')
print()

>>> a_ref : [ 7 66 17 81 39 47]
>>> a : [ 7 66 17 81 39 47]

>>> a_ref : [-1 -1 17 81 39 47]
>>> a : [-1 -1 17 81 39 47]

>>> a_ref : [[-1 -1 17]
 [81 39 47]]
>>> a : [[-1 -1 17]
 [81 39 47]]

>>> a_ref : [-1 -1 17 81 39 47]
>>> a : [-1 -1 17 81 39 47]



In [4]:
# copy by .view() -> vẫn Refer to the same object nhưng có shape riêng
a_view = a.view()
print(f'>>> a_view : {a_view}')
print(f'>>> a : {a}')
print()

# change the elem 
a_view[0] = 111
a[1] = 111
print(f'>>> a_view : {a_view}')
print(f'>>> a : {a}')
print()

# change the shape
a_view.shape = 3, -1, 2  # 3D array, 3xAutox2
print(f'>>> a_view : {a_view}')
print(f'>>> a : {a}')
print()

a.shape = 2, -1 # 2d, 2xAuto
print(f'>>> a_view : {a_view}')
print(f'>>> a : {a}')
print()

a.shape = -1
print(f'>>> a_view : {a_view}')
print(f'>>> a : {a}')
print()

>>> a_view : [-1 -1 17 81 39 47]
>>> a : [-1 -1 17 81 39 47]

>>> a_view : [111 111  17  81  39  47]
>>> a : [111 111  17  81  39  47]

>>> a_view : [[[111 111]]

 [[ 17  81]]

 [[ 39  47]]]
>>> a : [111 111  17  81  39  47]

>>> a_view : [[[111 111]]

 [[ 17  81]]

 [[ 39  47]]]
>>> a : [[111 111  17]
 [ 81  39  47]]

>>> a_view : [[[111 111]]

 [[ 17  81]]

 [[ 39  47]]]
>>> a : [111 111  17  81  39  47]



In [5]:
# copy by .copy() -> tạo đối tượng mới hoàn toàn, không liên quan gì tới object cũ
a_copy = a.copy()
print(f'>>> a_copy : {a_copy}')
print(f'>>> a : {a}')
print()

# change value
a_copy[0] = 999
a[1] = 999
print(f'>>> a_copy : {a_copy}')
print(f'>>> a : {a}')
print()

# change the shape
a_copy.shape = 6, 1, 1, 1, 1, 1 # 6D 6x1x1x1x1x1 array
print(f'>>> a_copy : {a_copy}')
print(f'>>> a : {a}')
print()

>>> a_copy : [111 111  17  81  39  47]
>>> a : [111 111  17  81  39  47]

>>> a_copy : [999 111  17  81  39  47]
>>> a : [111 999  17  81  39  47]

>>> a_copy : [[[[[[999]]]]]




 [[[[[111]]]]]




 [[[[[ 17]]]]]




 [[[[[ 81]]]]]




 [[[[[ 39]]]]]




 [[[[[ 47]]]]]]
>>> a : [111 999  17  81  39  47]



### concatenation

In [6]:
# np.concatenate((arrays), axis=None) # all array in arrays must have the same dimension
print(np.concatenate((a, b[0])))
print(np.concatenate((a, b[0], b[1])))
print()

# axis arg: 
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[7, 8, 9]])
print(c, d)
print()

# axis = 0 -> thêm thành hàng mới -> arrays ngoài việc cùng chiều thì cần cùng số cột
print(np.concatenate((c, d), axis=0)) # hoặc np.hstack((c, d))
# axis = 1 -> thêm thành cột mới -> ngoài việc cùng chiều thì số cột của c phải cùng số hàng của D
print(np.concatenate((c, d[0, :2].reshape(2, -1)), axis=1)) 
e = [[-1, -2], [-3, -4]]
print(np.concatenate((c, e), axis=1))# hoặc np.vstack((c,e))


[111 999  17  81  39  47  15  17  69  96]
[111 999  17  81  39  47  15  17  69  96  24  47  82  45]

[[1 2 3]
 [4 5 6]] [[7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 7]
 [4 5 6 8]]
[[ 1  2  3 -1 -2]
 [ 4  5  6 -3 -4]]
