# Sorting
- `array.sort()`
- `array.argsort()`
- reverse the sort order

In [1]:
import numpy as np

a = np.random.randint(1, 100, 10)
b = np.random.randint(1, 100, (2, 5))
print(a)
print(b)

[30 66 56 28 30  7 31 77 99 82]
[[67 76 39 38 82]
 [93 99 38 99 37]]


In [2]:
# np.sort() & axis -> return a copy of array, sorted
# np.sort(array, axis)

# with 1D array => mặc định xếp tăng dần, không cần chỉ định axis
print(np.sort(a))

# with 2d array
# 1. không chỉ định axis hoặc axis=-1 (default) -> sắp xếp theo trục cuối của mảng
# ex: mxn arr -> sort theo trục n // mxnxp -> sort theo p
print(np.sort(b)) # 2x5 arr -> trục cột 

# 2. axis=None => chuyển thành 1D xong sort
print(np.sort(b, axis=None))

# 3. axis = 0 => sort theo hàng -> tức là lấy phần tử tương ứng ở các hàng, không phải sort trên 1 hàng 
# sort các phần tử ở vị trí j trên mỗi hàng, tức là sort cột j
print(np.sort(b, axis=0)) 

# 4. axis = 1 => sort theo cột -> các cột khác nhau ở 1 hàng (sort trên 1 hàng)
print(np.sort(b, axis=1))

# 5. axis = n -> sort theo trục n


# kết quả sort là mảng mới copy từ mảng cũ và không có liên hệ với mảng cũ
print()
c = np.sort(a)
print(a, c)
c[0] = -1
print(a, c)
c.shape = 2, -1
print(a)
print(c)

# reverse sorting order
print(np.sort(a)[::-1])

[ 7 28 30 30 31 56 66 77 82 99]
[[38 39 67 76 82]
 [37 38 93 99 99]]
[37 38 38 39 67 76 82 93 99 99]
[[67 76 38 38 37]
 [93 99 39 99 82]]
[[38 39 67 76 82]
 [37 38 93 99 99]]

[30 66 56 28 30  7 31 77 99 82] [ 7 28 30 30 31 56 66 77 82 99]
[30 66 56 28 30  7 31 77 99 82] [-1 28 30 30 31 56 66 77 82 99]
[30 66 56 28 30  7 31 77 99 82]
[[-1 28 30 30 31]
 [56 66 77 82 99]]
[99 82 77 66 56 31 30 30 28  7]


In [3]:
# array.sort -> sort trực tiếp trên array
c = a.copy()
print(c)

c.sort()
print(c)

#axis=-1
c = b.copy()
print(c)
#axis=0
c.sort(axis=0)
print(c)
#axis=1
c.sort(axis=1)
print(c)

# c.sort(axis=None) # error vì làm thay đổi trực tiếp shape của c

[30 66 56 28 30  7 31 77 99 82]
[ 7 28 30 30 31 56 66 77 82 99]
[[67 76 39 38 82]
 [93 99 38 99 37]]
[[67 76 38 38 37]
 [93 99 39 99 82]]
[[37 38 38 67 76]
 [39 82 93 99 99]]


In [4]:
# argsort -> trả về chỉ số của phần tử sau khi sort (indecies)
names = np.array(['kkk', 'abc', 'random'])
scores = np.random.randint(0, 11, 3)

indices = scores.argsort() # không thay đổi mảng // or: indices = np.argsort(scores)
print(names[indices])

# reverse order:
indices = indices[::-1]
print(names[indices], scores[indices], sep='\n')

print(b.argsort(axis=0))
print(b.argsort(axis=1))

['random' 'kkk' 'abc']
['abc' 'kkk' 'random']
[9 4 2]
[[0 0 1 0 1]
 [1 1 0 1 0]]
[[3 2 0 1 4]
 [4 2 0 1 3]]
